const fruits=["orange","apple","promogranate","beetroot"];
console.log(fruits.toString());
console.log(fruits.join("*"));
console.log(fruits.pop());
console.log(fruits);
console.log(fruits.push("juice"));
console.log(fruits);
console.log(fruits.shift());
console.log(fruits);
console.log(fruits.unshift("juice"));
console.log(fruits);
fruits[0]="kiwi";
console.log(fruits);
console.log(fruits[fruits.length]="grapes");
console.log(fruits);
const mygirl=["su","ko"];
const myboy=["jin","rum"];
const mychild=mygirl.concat(myboy);
console.log(mychild);
console.log(mychild.concat("sim")); 
fruits.splice(2,0,"lemon","jivi");
console.log(fruits);
const child=["sim","sum","rim","gum"];
child.splice(2,2,"lum","kum");
console.log(child);
console.log(child.slice(1));
